#!/usr/bin/ruby
# encoding: utf-8

####################################################################################################
################################### establish project environment ##################################
####################################################################################################
load './config/antlr3.rb'

def run_task( name )
  Rake::Task.task_defined?( name ) or file( name )
  case task = Rake::Task[ name ]
  when Rake::FileTask then task.needed? and task.invoke
  else task.invoke
  end
end
def abs( path ); File.expand_path( path ); end
def rel( path, dir = '.' ); File.relative_path( path, dir ); end


####################################################################################################
######################################### task definitions #########################################
####################################################################################################

# tasks concerning the development environment
task :update do
  $project.load_task 'update_gems'
end

desc "update gems and setup project development environment"
task :setup => %w( update ) do
  $project.load_environment
end

# task :default => %w( setup )
# $project.setup? or run_task( :setup )

if $project.setup?
  
  # tasks concerning the ANTLR java package
  desc "update the antlr jar if necessary"
  task :antlr do
    $project.load_task 'antlr'
  end
  
  for task_lib in %w( notes package publish test doc )
    $project.load_task( task_lib )
  end
  
  desc( "clean up all project by-products" )
  task :clean => %w( test:clean package:clobber doc:clobber doc:samples:clobber )
else
  puts( <<-END.here_indent! )
  | ** Note **
  | The development environment has not been established.
  | Thus, most rake tasks will not be active until you run:
  | 
  |   ruby ./setup.rb
  | 
  END
end