/** \file
 *  This C header file was generated by $ANTLR version 3.2.1-SNAPSHOT Dec 18, 2009 04:29:28
 *
 *     -  From the grammar source file : CSS.g
 *     -                            On : 2010-01-02 19:55:29
 *     -                 for the lexer : CSSLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer CSS has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pCSS, which is returned from a call to CSSNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pCSS are  as follows:
 *
 *  -  void      pCSS->WS(pCSS)
 *  -  void      pCSS->COMMENT(pCSS)
 *  -  void      pCSS->STRING(pCSS)
 *  -  void      pCSS->IMPORTANT(pCSS)
 *  -  void      pCSS->NUMBER(pCSS)
 *  -  void      pCSS->ID(pCSS)
 *  -  void      pCSS->AT_KEYWORD(pCSS)
 *  -  void      pCSS->HASH(pCSS)
 *  -  void      pCSS->URI(pCSS)
 *  -  void      pCSS->UNICODE_RANGE(pCSS)
 *  -  void      pCSS->DELIM(pCSS)
 *  -  void      pCSS->PLAIN_ID(pCSS)
 *  -  void      pCSS->NONASCII(pCSS)
 *  -  void      pCSS->HEX(pCSS)
 *  -  void      pCSS->ESCAPE(pCSS)
 *  -  void      pCSS->NEWLINE(pCSS)
 *  -  void      pCSS->S(pCSS)
 *  -  void      pCSS->Tokens(pCSS)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_CSS_H
#define _CSS_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct CSS_Ctx_struct CSS, * pCSS;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for CSS
 */
struct CSS_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mWS)	(struct CSS_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct CSS_Ctx_struct * ctx);
     void (*mSTRING)	(struct CSS_Ctx_struct * ctx);
     void (*mIMPORTANT)	(struct CSS_Ctx_struct * ctx);
     void (*mNUMBER)	(struct CSS_Ctx_struct * ctx);
     void (*mID)	(struct CSS_Ctx_struct * ctx);
     void (*mAT_KEYWORD)	(struct CSS_Ctx_struct * ctx);
     void (*mHASH)	(struct CSS_Ctx_struct * ctx);
     void (*mURI)	(struct CSS_Ctx_struct * ctx);
     void (*mUNICODE_RANGE)	(struct CSS_Ctx_struct * ctx);
     void (*mDELIM)	(struct CSS_Ctx_struct * ctx);
     void (*mPLAIN_ID)	(struct CSS_Ctx_struct * ctx);
     void (*mNONASCII)	(struct CSS_Ctx_struct * ctx);
     void (*mHEX)	(struct CSS_Ctx_struct * ctx);
     void (*mESCAPE)	(struct CSS_Ctx_struct * ctx);
     void (*mNEWLINE)	(struct CSS_Ctx_struct * ctx);
     void (*mS)	(struct CSS_Ctx_struct * ctx);
     void (*mTokens)	(struct CSS_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct CSS_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pCSS CSSNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pCSS CSSNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define FUNCTION      6
#define UNICODE_RANGE      29
#define ANGLE      8
#define NUMBER      21
#define HASH      25
#define S      26
#define DELIM      30
#define ID      23
#define EOF      -1
#define INVALID      7
#define PERCENTAGE      4
#define LENGTH      9
#define IMPORTANT      19
#define URI      27
#define TIME      11
#define WS      14
#define NEWLINE      16
#define ESCAPE      17
#define HEX      28
#define EMS      12
#define EXS      13
#define PLAIN_ID      20
#define DIMENSION      5
#define FREQ      10
#define AT_KEYWORD      24
#define COMMENT      15
#define NONASCII      22
#define STRING      18
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for CSS
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
