/** \file
 *  This C header file was generated by $ANTLR version 3.2.1-SNAPSHOT Dec 18, 2009 04:29:28
 *
 *     -  From the grammar source file : CSS.g
 *     -                            On : 2010-01-02 19:47:03
 *     -                for the parser : CSSParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser CSSParser has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pCSSParser, which is returned from a call to CSSParserNew().
 *
 * The methods in pCSSParser are  as follows:
 *
 *  - void      pCSSParser->stylesheet(pCSSParser)
 *  - void      pCSSParser->import_statement(pCSSParser)
 *  - void      pCSSParser->media(pCSSParser)
 *  - void      pCSSParser->media_list(pCSSParser)
 *  - void      pCSSParser->page(pCSSParser)
 *  - void      pCSSParser->rule_set(pCSSParser)
 *  - void      pCSSParser->selector(pCSSParser)
 *  - void      pCSSParser->simple_selector(pCSSParser)
 *  - void      pCSSParser->klass(pCSSParser)
 *  - void      pCSSParser->element_name(pCSSParser)
 *  - void      pCSSParser->attrib(pCSSParser)
 *  - void      pCSSParser->pseudo(pCSSParser)
 *  - void      pCSSParser->declaration(pCSSParser)
 *  - void      pCSSParser->expr(pCSSParser)
 *  - void      pCSSParser->term(pCSSParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_CSSParser_H
#define _CSSParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct CSSParser_Ctx_struct CSSParser, * pCSSParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for CSSParser
 */
struct CSSParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;


     void (*stylesheet)	(struct CSSParser_Ctx_struct * ctx);
     void (*import_statement)	(struct CSSParser_Ctx_struct * ctx);
     void (*media)	(struct CSSParser_Ctx_struct * ctx);
     void (*media_list)	(struct CSSParser_Ctx_struct * ctx);
     void (*page)	(struct CSSParser_Ctx_struct * ctx);
     void (*rule_set)	(struct CSSParser_Ctx_struct * ctx);
     void (*selector)	(struct CSSParser_Ctx_struct * ctx);
     void (*simple_selector)	(struct CSSParser_Ctx_struct * ctx);
     void (*klass)	(struct CSSParser_Ctx_struct * ctx);
     void (*element_name)	(struct CSSParser_Ctx_struct * ctx);
     void (*attrib)	(struct CSSParser_Ctx_struct * ctx);
     void (*pseudo)	(struct CSSParser_Ctx_struct * ctx);
     void (*declaration)	(struct CSSParser_Ctx_struct * ctx);
     void (*expr)	(struct CSSParser_Ctx_struct * ctx);
     void (*term)	(struct CSSParser_Ctx_struct * ctx);
    // Delegated rules
    const char * (*getGrammarFileName)();
    void	    (*free)   (struct CSSParser_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pCSSParser CSSParserNew         (pANTLR3_COMMON_TOKEN_STREAM instream);
ANTLR3_API pCSSParser CSSParserNewSSD      (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the parser will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define FUNCTION      6
#define UNICODE_RANGE      29
#define DELIM      30
#define ID      16
#define EOF      -1
#define LENGTH      9
#define TIME      11
#define T__51      51
#define T__52      52
#define ESCAPE      23
#define T__53      53
#define HEX      28
#define DIMENSION      5
#define FREQ      10
#define AT_KEYWORD      26
#define COMMENT      21
#define T__50      50
#define T__42      42
#define T__43      43
#define T__40      40
#define T__41      41
#define T__46      46
#define T__47      47
#define T__44      44
#define ANGLE      8
#define T__45      45
#define T__48      48
#define T__49      49
#define NUMBER      19
#define HASH      17
#define S      27
#define INVALID      7
#define PERCENTAGE      4
#define IMPORTANT      18
#define URI      15
#define T__31      31
#define T__32      32
#define T__33      33
#define WS      20
#define T__34      34
#define NEWLINE      22
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define EMS      12
#define T__39      39
#define EXS      13
#define PLAIN_ID      24
#define NONASCII      25
#define STRING      14
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for CSSParser
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
