#!/usr/bin/env ruby
# encoding: utf-8

=begin      ::about::
author:     Kyle Yetter <kcy5b@yahoo.com>
created on: October 18, 2009
purpose:    utility script
summary:    convert textile-based documentation files to HTML
=end

__DIR__ = File.dirname( __FILE__ )
load File.join( __DIR__, 'script-helper.rb' )

require 'main'
require 'doc-utils'

Main do
  argument( :files ) do
    description( "documentation files" )
    arity( -2 )
  end
  
  def run
    for file in params[ :files ].values
      ANTLRDoc.convert( file )
    end
  end
end
