#!/usr/bin/env ruby-script
# encoding: utf-8

__DIR__ = File.dirname( __FILE__ )
load File.join( __DIR__, 'script-helper.rb' )

require 'highlight'

Main do
  
  argument :grammar_file do
    description( "path to an ANTLR v3 grammar file" )
    validate { |f| test(?f, f) }
    arity(1)
  end
  
  def run
    grammar_file = params[ :grammar_file ].value
    highlight = Highlight::Languages::ANTLR.load( grammar_file )
    puts highlight.full_document
  end
  
end
