#!/usr/bin/env ruby-script
# encoding: utf-8

Ruby.setup(
  :project => 'antlr3',
  :load_gems => true
)

establish 'cli-optparse'
require 'antlr3'
project.test_mode!
require 'antlr-highlighter'

$out_dir = '.'
$auto_name = false
OptionParser.new do |op|
  op.on('--[no-]auto', "write output to NAME.html instead of $stdout, where NAME is the grammar's name") do |b|
    $auto_name = b
  end
  op.on('--directory=DIR', "if using auto_name, write output file to directory DIR") do |dir|
    $out_dir = dir
  end
end.parse(ARGV)

high = $stdin.tty? ? ANTLRHighlighter.load(ARGV.shift) : ANTLRHighlighter.new($stdin.read)
if $auto_name
  high.write_to_file($out_dir)
else
  high.full_document($stdout)
end
