#!/bin/sh

##!/home/kyle/lib/shell/bin/bare-ruby
#require 'shellwords'
#this_dir = File.expand_path(File.dirname(File.dirname(__FILE__)))
#jar_path = File.join(this_dir, 'java', 'antlr-full-3.1.3.jar')
##cpath.unshift(jar_path)
#
#ENV['CLASSPATH'] = jar_path
#
#cmd = ('java -server org.antlr.Tool %s' % ARGV.shelljoin).tap { |i| i.strip! }
#exec(cmd)


jar_path=$(dirname $(dirname $0))/java/antlr-full-3.2.jar
CLASSPATH=$jar_path
export CLASSPATH
java -server org.antlr.Tool $@